spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size : 100MB
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

#aws image upload
cloud:
  aws:
    credentials:
      accessKey : ${{ secrets.AWS_ACCESS_KEY }} #AWS IAM AccessKey in github secret #${AWS_ACCESS_KEY_ID}
      secretKey : ${{ secrets.AWS_SECRET_ACCESS_KEY }} #AWS IAM SecretKey in github secret #${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: "jbawsbucket1"
      dir : "/itemImg"
    region:
      static: ap-northeast-2
    stack:
      auto : false
