spring:
  redis:
    host: localhost
    port: 6379
    password: 'sebbe41main02fightingsebbe41main02fightingsebbe41main02fighting' #${{secrets.BE_REDIS_SCRET_KEY}} #'sebbe41main02fightingsebbe41main02fightingsebbe41main02fighting'

#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    url: jdbc:mysql://jb-database-instance1.cwxmdz6g5fnu.ap-northeast-2.rds.amazonaws.com:13306/jbdatabase1?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: '!rmsfhrkaehr2rhkJB!'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/import.sql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size : 100MB
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true

#aws image upload
cloud:
  aws:
    credentials:
      accessKey : 1234 #${{ secrets.BE_AWS_ACCESS_KEY }}  #AWS IAM AccessKey in github secret #${AWS_ACCESS_KEY_ID}
      secretKey : 1234 #${{ secrets.BE_AWS_SECRET_ACCESS_KEY }}  #AWS IAM SecretKey in github secret #${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: "jbawsbucket1"
      dir : "/itemImg"
    region:
      static: ap-northeast-2
    stack:
      auto : false
mail:
  address:
    admin: "admin@gmail.com"
jwt:
  key: sdfkjsakldfjskldfjaskldfjasklfjaskldfj
  access-token-expiration-minutes: 20
  refresh-token-expiration-minutes: 420
